# Template: https://github.com/starkat99/appveyor-rust

os: Visual Studio 2017

## Build Matrix ##

# You may use the `cargoflags` and `RUSTFLAGS` variables to set additional flags
# for cargo commands and rustc, respectively.
environment:
  matrix:

    ### MSVC Toolchains ###

    # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
    # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
    # Beta 64-bit MSVC
    # - channel: beta
      # target: x86_64-pc-windows-msvc
    # Beta 32-bit MSVC
    # - channel: beta
      # target: i686-pc-windows-msvc
    # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
      #cargoflags: --features "unstable"
    # Nightly 32-bit MSVC
    - channel: nightly
      target: i686-pc-windows-msvc
      #cargoflags: --features "unstable"

    ### GNU Toolchains ###

    # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
    # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu
    # Beta 64-bit GNU
    - channel: beta
      target: x86_64-pc-windows-gnu
    # Beta 32-bit GNU
    - channel: beta
      target: i686-pc-windows-gnu
    # Nightly 64-bit GNU
    - channel: nightly
      target: x86_64-pc-windows-gnu
      #cargoflags: --features "unstable"
    # Nightly 32-bit GNU
    - channel: nightly
      target: i686-pc-windows-gnu
      #cargoflags: --features "unstable"

matrix:
  allow_failures:
    - channel: nightly
    - channel: beta

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: off

artifacts:
  - name: minittc-%channel%-%target%.exe
    path: target\release\minittc.exe

test_script:
  - cargo build --release --bin minittc --all-features
  - cargo test --verbose --all-features %cargoflags%
